#!/bin/bash -e
set -e
mkdir -p /etc/dconf/db/local.d/
rsync -a --delete /usr/lib/foxxy-skel/etc/skel /etc/
cp -r /usr/lib/foxxy-skel/etc/dconf/db/local.d/foxxy-skel /etc/dconf/db/local.d/foxxy-skel
dconf compile /etc/dconf/db/local /etc/dconf/db/local.d/
dconf compile /etc/skel/.config/dconf/user /etc/dconf/db/local.d/
